# assistant_mapping.py

# Map all possible technical names to a single display name
TECHNICAL_TO_DISPLAY = {
    "qodo": "Qodo",
    "pycharm": "AI Assistant in PyCharm",
    "cursor": "Cursor",
    "aider": "Aider",
    "amazonq": "Amazon Q",
    "jetbrain_junie": "JetBrains Junie",
    "jetbrains_junie": "JetBrains Junie",
    "zed": "Zed Editor",
    "zededitor": "Zed Editor",
    "sourcegraph": "Sourcegraph",
    "github_copilot": "GitHub Copilot",
    "codex_edu": "Codex in ChatGPT Edu",
    "codexedu": "Codex in ChatGPT Edu",
    "codex": "Codex",
    "cline": "Cline",
    "trae": "Trae",
    "windsurf": "Windsurf",
    "firebase": "Firebase",
    "replit": "Replit",
    "tabnine": "Tabnine",
    "tabbyml": "TabbyML",
}

# Assign a unique color to each display name
DISPLAY_TO_COLOR = {
    "Qodo": "#1f77b4",
    "AI Assistant in PyCharm": "#ff7f0e",
    "Cursor": "#2ca02c",
    "Aider": "#d62728",
    "Amazon Q": "#9467bd",
    "JetBrains Junie": "#8c564b",
    "Zed Editor": "#e377c2",
    "Sourcegraph": "#7f7f7f",
    "GitHub Copilot": "#bcbd22",
    "Codex in ChatGPT Edu": "#17becf",
    "Codex": "#aec7e8",
    "Cline": "#ffbb78",
    "Trae": "#98df8a",
    "Windsurf": "#ff9896",
    "Firebase": "#c5b0d5",
    "Replit": "#c49c94",
    "Tabnine": "#f7b6d2",
    "TabbyML": "#dbdb8d",
}

GENERAL_LLM_TECHNICAL_TO_DISPLAY = {
    "nvidia_llama3": "NVIDIA Llama 3",
    "deepseek_v3": "DeepSeek V3",
    "nous_hermes3": "Nous Hermes 3",
    "gemini1_5": "Gemini 1.5",
    "claude3_5sonnet": "Claude 3.5 Sonnet",
    "meta_llama3": "Meta Llama 3",
    "thudm_glm4": "THUDM GLM-4",
    "dolphin_mixtral": "Dolphin Mixtral",
    "nova_pro": "Nova Pro",
    "gpt4": "GPT-4",
    "qwen2": "Qwen 2",
    "grok2": "Grok 2",
    "phi4": "Phi-4",
    "01ai_yi": "01.AI Yi",
    "cohere_commandr": "Cohere Command-R",
    "perplexity_sonar": "Perplexity Sonar",
    "a21_jamba": "A21 Jamba",
    "sarvam_m": "Sarvam M",
    "mythomax": "MythoMax",
    "mythalion": "Mythalion",
} 